package com.briup.queue.qcheck.bean;

public class VipUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user.id
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user.user_name
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user.type
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user.id
     *
     * @return the value of vip_user.id
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user.id
     *
     * @param id the value for vip_user.id
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user.user_name
     *
     * @return the value of vip_user.user_name
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user.user_name
     *
     * @param userName the value for vip_user.user_name
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user.type
     *
     * @return the value of vip_user.type
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user.type
     *
     * @param type the value for vip_user.type
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}