package com.briup.queue.qcheck.dao;

import com.briup.queue.qcheck.bean.DbUser;
import com.briup.queue.qcheck.bean.DbUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    long countByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int deleteByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int insert(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int insertSelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    List<DbUser> selectByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    DbUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") DbUser record, @Param("example") DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int updateByExample(@Param("record") DbUser record, @Param("example") DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int updateByPrimaryKeySelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbg.generated Wed Mar 04 16:03:37 CST 2020
     */
    int updateByPrimaryKey(DbUser record);
}