package com.briup.queue.qcheck.dao;

import com.briup.queue.qcheck.bean.MoneyUser;
import com.briup.queue.qcheck.bean.MoneyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoneyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    long countByExample(MoneyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int deleteByExample(MoneyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int insert(MoneyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int insertSelective(MoneyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    List<MoneyUser> selectByExample(MoneyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    MoneyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") MoneyUser record, @Param("example") MoneyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByExample(@Param("record") MoneyUser record, @Param("example") MoneyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByPrimaryKeySelective(MoneyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByPrimaryKey(MoneyUser record);
}