package com.briup.queue.qcheck.dao;

import com.briup.queue.qcheck.bean.VipUser;
import com.briup.queue.qcheck.bean.VipUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    long countByExample(VipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int deleteByExample(VipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int insert(VipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int insertSelective(VipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    List<VipUser> selectByExample(VipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    VipUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") VipUser record, @Param("example") VipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByExample(@Param("record") VipUser record, @Param("example") VipUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByPrimaryKeySelective(VipUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_user
     *
     * @mbg.generated Wed Mar 04 16:03:38 CST 2020
     */
    int updateByPrimaryKey(VipUser record);
}